import Q1

#print axioms Q1.mem_imageBlock
#print axioms Q1.card_imageBlock
#print axioms Q1.imageBlock_one
#print axioms Q1.imageBlock_mul
#print axioms Q1.imageBlock_inv
#print axioms Q1.imageBlock_inv'
#print axioms Q1.imageBlock_disjoint_iff
#print axioms Q1.imageBlock_disjoint
#print axioms Q1.imageBlock_mono
#print axioms Q1.mem_orbitBall
#print axioms Q1.orbitBall_mono
#print axioms Q1.orbitBall_transfer
#print axioms Q1.orbitBall_transfer_of_le
#print axioms Q1.orbitBall_subset_imageBlocks_union
#print axioms Q1.orbitBall_card_le_imageBlocks
#print axioms Q1.imageBlock_subset_blockUnion
#print axioms Q1.card_blockUnion_le
#print axioms Q1.card_blockUnion
#print axioms Q1.greedy_disjoint_blocks
#print axioms Q1.OrdinarySRD.exists_global_exp_bound
#print axioms Q1.tendsto_srd_log_radius
#print axioms Q1.eventually_srd_log_radius_lt_one
#print axioms Q1.tendsto_srd_log_radius_without_divergence
#print axioms Q1.eventually_srd_log_radius_lt_one_without_divergence
#print axioms Q1.tendsto_srd_packing_bound
#print axioms Q1.false_of_srd_packing_lower_bound
#print axioms Q1.ordinarySRD_of_polynomial_bound
#print axioms Q1.blockMultiplicity_eq_pair_count
#print axioms Q1.translators_injective
#print axioms Q1.blockMultiplicity_le_one
#print axioms Q1.blockMultiplicity_eq_one
#print axioms Q1.blockMultiplicity_eq_zero
#print axioms Q1.uniformBlockCoefficient_on_union
#print axioms Q1.uniformBlockCoefficient_off_union
#print axioms Q1.uniformBlockCoefficient_energy
#print axioms Q1.conjugationLengthBall_length
#print axioms Q1.imageBlock_toConjAct
#print axioms Q1.conjugation_orbitBall
#print axioms Q1.conjugate_length_le
#print axioms Q1.conjugateBlock_subset_ball
#print axioms Q1.representedWithin_self
#print axioms Q1.representedWithin_image
#print axioms Q1.representedWithin_mono
#print axioms Q1.displacement_cost
#print axioms Q1.sunflower_threshold_mono
#print axioms Q1.finite_threshold_displacement
#print axioms Q1.finite_threshold_packing
#print axioms Q1.packingEnvelope_pos
#print axioms Q1.packing_threshold_le_envelope
#print axioms Q1.packing_threshold_lt_envelope
#print axioms Q1.packing_threshold_lt_exp
#print axioms Q1.packingLogInput_nonneg
#print axioms Q1.packingLogK_pos
#print axioms Q1.packingLogB_nonneg
#print axioms Q1.exponentialPackingRadius_le_log
#print axioms Q1.exponential_growth_packing
#print axioms Q1.exponential_growth_logarithmic_packing
#print axioms Q1.confined_subgroup_ball_card
#print axioms Q1.one_le_normalized_of_nat_le_sq
#print axioms Q1.no_confined_subgroup_of_exponential_growth_and_srd_volume
#print axioms Q1.exists_sunflower
#print axioms Q1.exists_disjoint_of_sunflower
#print axioms Q1.mem_wordBall_iff
#print axioms Q1.exists_word_of_generates
#print axioms Q1.exists_mem_wordBall
#print axioms Q1.wordLength_le_iff
#print axioms Q1.wordLength_one
#print axioms Q1.wordLength_mul
#print axioms Q1.wordLength_inv
#print axioms Q1.wordLengthBall_length_le_iff
#print axioms Q1.exists_word_length_eq
#print axioms Q1.wordLengthBall_length_eq_zero_iff
#print axioms Q1.wordLengthBall
#print axioms Q1.conjugate_eq_iff_relative_commutes
#print axioms Q1.conjugate_generators_eq_iff_mk_eq
#print axioms Q1.centerConjugacyTuple_mk
#print axioms Q1.centerConjugacyTuple_injective
#print axioms Q1.wordBall_image
#print axioms Q1.mem_wordBall_image_lift
#print axioms Q1.length_map_list_prod_le
#print axioms Q1.length_map_wordBall_le
#print axioms Q1.mem_tupleAlphabet
#print axioms Q1.tupleAlphabet_inv_mem
#print axioms Q1.tupleAlphabet_generates
#print axioms Q1.quotientTupleAlphabet_generates
#print axioms Q1.quotientTupleAlphabet_inv_mem
#print axioms Q1.tupleAlphabet_ambient_length_le
#print axioms Q1.quotient_wordBall_bounded_lift
#print axioms Q1.quotient_center_wordBall_card_le_conjugacy
#print axioms Q1.conjugacyGrowthRate_pos
#print axioms Q1.conjugacyGrowthConstant_pos
#print axioms Q1.conjugacyGrowthConstant_le_one
#print axioms Q1.exponential_lower_bound_of_sampled_power
#print axioms Q1.translateBoundary_one
#print axioms Q1.translateBoundary_mul_card_le
#print axioms Q1.translateBoundary_word_card_le
#print axioms Q1.finiteFoelner_of_generatorFoelner
#print axioms Q1.finiteFoelner_iff_generatorFoelner
#print axioms Q1.translateBoundary_subset_generatorBoundary
#print axioms Q1.exists_generator_expansion_of_not_finiteFoelner
#print axioms Q1.wordBall_nonempty
#print axioms Q1.wordBall_succ_card
#print axioms Q1.exponential_wordBall_of_generator_expansion
#print axioms Q1.exponential_wordBall_of_not_finiteFoelner
#print axioms Q1.leftTranslate_image_hom
#print axioms Q1.translateBoundary_image_hom
#print axioms Q1.foelner_set_of_injective_hom
#print axioms Q1.finiteFoelner_of_locally
#print axioms Q1.finiteFoelner_of_finite
#print axioms Q1.exists_finset_of_mem_closure
#print axioms Q1.exists_finset_stage
#print axioms Q1.finiteFoelner_closure_of_finite_stages
#print axioms Q1.exists_not_finiteFoelner_finset_stage
#print axioms Q1.exists_not_finiteFoelner_normalClosure_stage
#print axioms Q1.exists_nonempty_not_finiteFoelner_finset_stage
#print axioms Q1.conjugacyBall_mono
#print axioms Q1.conjugacyBall_nonempty
#print axioms Q1.exponential_conjugacy_growth_of_quotient_not_finiteFoelner
#print axioms Q1.uniform_exponential_constants
#print axioms Q1.finsetClosureTuple_generates
#print axioms Q1.finsetClosureTuple_mem
#print axioms Q1.exists_conjugate_tuple_not_finiteFoelner
#print axioms Q1.exponential_conjugacy_growth_of_witness
#print axioms Q1.no_confined_subgroup_of_quotient_witnesses_and_srd_volume
#print axioms Q1.leftTranslate_symmDiff_card
#print axioms Q1.coe_leftTranslate
#print axioms Q1.hasInvariantMean_of_finiteFoelner
#print axioms Q1.wordBall_card_le_pow_card
#print axioms Q1.generatorFoelner_of_polynomial_wordBall
#print axioms Q1.generatorFoelner_of_commutative
#print axioms Q1.finiteFoelner_of_commutative
#print axioms Q1.finiteFoelner_center
#print axioms Q1.IsAmenableRadical.unique
#print axioms Q1.amenableNormalCover_bot_iff
#print axioms Q1.not_finiteFoelner_normalClosure_of_amenableNormalCover
#print axioms Q1.not_finiteFoelner_normalClosure_of_outside_radical
#print axioms Q1.mem_leftTranslate_iff
#print axioms Q1.mem_translateBoundary_iff
#print axioms Q1.extensionPair_quotient
#print axioms Q1.extensionPair_injective
#print axioms Q1.mem_extensionSet_iff
#print axioms Q1.extensionSet_card
#print axioms Q1.extensionSet_nonempty
#print axioms Q1.extensionCocycle_identity
#print axioms Q1.extensionBad_card_le
#print axioms Q1.extensionBoundary_subset
#print axioms Q1.extensionBoundary_card_le
#print axioms Q1.finiteFoelner_extension
#print axioms Q1.finiteFoelner_of_center_quotient
#print axioms Q1.quotient_witness_of_not_finiteFoelner_normalClosure
#print axioms Q1.quotient_witness_of_amenableNormalCover
#print axioms Q1.exponential_conjugacy_growth_of_amenableNormalCover
#print axioms Q1.exponential_conjugacy_growth_outside_radical
#print axioms Q1.exponential_conjugacy_growth_wordLength
#print axioms Q1.isAmenableRadical_bot_iff
#print axioms Q1.no_confined_subgroup_of_trivial_radical_srd_volume
#print axioms Q1.no_confined_subgroup_of_trivial_radical_rd_volume
#print axioms Q1.centerConjugacyTuple
#print axioms Q1.tupleAlphabet
#print axioms Q1.quotientTupleAlphabet
#print axioms Q1.conjugacyGrowthRate
#print axioms Q1.conjugacyGrowthConstant
#print axioms Q1.leftTranslate
#print axioms Q1.translateBoundary
#print axioms Q1.FiniteFoelner
#print axioms Q1.GeneratorFoelner
#print axioms Q1.generatorBoundary
#print axioms Q1.conjugacyBall
#print axioms Q1.finsetClosureTuple
#print axioms Q1.NonFoelnerCenterQuotientWitness
#print axioms Q1.HasInvariantMean
#print axioms Q1.translateSymmDiff
#print axioms Q1.AmenableNormalCover
#print axioms Q1.extensionPair
#print axioms Q1.extensionSet
#print axioms Q1.extensionCocycle
#print axioms Q1.extensionBad
#print axioms Q1.IsAmenableRadical.mk
#print axioms Q1.leftRegular_apply
#print axioms Q1.norm_leftRegular_apply
#print axioms Q1.leftRegular_one
#print axioms Q1.leftRegular_mul
#print axioms Q1.leftRegular_single
#print axioms Q1.norm_leftRegular
#print axioms Q1.regularConvolution_apply
#print axioms Q1.regularConvolution_single
#print axioms Q1.regularConvolution_zero
#print axioms Q1.norm_regularConvolution_le
#print axioms Q1.coefficientVector_apply
#print axioms Q1.coefficientL2Norm_sq
#print axioms Q1.coefficientVector_single
#print axioms Q1.coefficientL2Norm_single
#print axioms Q1.regularConvolution_delta
#print axioms Q1.coefficientL2Norm_le_norm_regularConvolution
#print axioms Q1.coefficientVector_zero
#print axioms Q1.coefficientVector_injective
#print axioms Q1.coefficientVector_eq_zero
#print axioms Q1.coefficientL2Norm_zero
#print axioms Q1.coefficientL2Norm_nonneg
#print axioms Q1.coefficientL2Norm_eq_zero
#print axioms Q1.coefficientL2Norm_pos
#print axioms Q1.coefficientVector_add
#print axioms Q1.coefficientVector_smul
#print axioms Q1.coefficientL2Norm_smul
#print axioms Q1.regularConvolution_eq_zero
#print axioms Q1.regularConvolution_add
#print axioms Q1.regularConvolution_smul
#print axioms Q1.sum_norm_le_sqrt_card_mul_sqrt_sum
#print axioms Q1.ratio_le_sqrt_card_of_norm_bound
#print axioms Q1.ordinarySRD_iff_log_limit
#print axioms Q1.log_limit_of_polynomial_bound
#print axioms Q1.norm_regularConvolution_le_sqrt_card
#print axioms Q1.reducedRatio_le_sqrt_card
#print axioms Q1.reducedRatios_bddAbove
#print axioms Q1.reducedRatios_nonempty
#print axioms Q1.reducedRatio_nonneg
#print axioms Q1.reducedRatio_le_rho
#print axioms Q1.reducedBallRho_nonneg
#print axioms Q1.reducedBallRho_le_sqrt_card
#print axioms Q1.reducedBallRho_mono
#print axioms Q1.reducedRatio_single_one
#print axioms Q1.one_le_reducedBallRho
#print axioms Q1.norm_regularConvolution_le_rho_mul
#print axioms Q1.one_le_reducedRho
#print axioms Q1.reducedRho_nonneg
#print axioms Q1.reducedRho_le_sqrt_card
#print axioms Q1.reducedRho_monotone
#print axioms Q1.reducedSRD_iff_ordinarySRD
#print axioms Q1.ReducedRD.subrapid
#print axioms Q1.nonzeroReducedRatios_subset
#print axioms Q1.nonzeroReducedRatios_bddAbove
#print axioms Q1.one_mem_nonzeroReducedRatios
#print axioms Q1.reducedBallRho_eq_sSup_nonzero
#print axioms Q1.mean_image_eq_of_piecewise_leftTranslate
#print axioms Q1.no_doubling_map_of_hasInvariantMean
#print axioms Q1.exists_doubling_map_of_finset_expansion
#print axioms Q1.exists_finset_expansion_of_not_finiteFoelner
#print axioms Q1.exists_finset_doubling_of_not_finiteFoelner
#print axioms Q1.finiteFoelner_of_hasInvariantMean
#print axioms Q1.hasInvariantMean_iff_finiteFoelner
#print axioms Q1.indicatorVector_apply
#print axioms Q1.inner_indicatorVector_left
#print axioms Q1.indicatorVector_norm_sq
#print axioms Q1.mem_leftTranslate_iff_inv_mul
#print axioms Q1.inner_indicatorVector_leftRegular
#print axioms Q1.re_inner_indicatorVector_leftRegular
#print axioms Q1.translateBoundary_image_card
#print axioms Q1.exists_ambient_foelner_set
#print axioms Q1.norm_sum_leftRegular_le_card
#print axioms Q1.card_mul_one_sub_le_norm_sum_leftRegular_of_boundary
#print axioms Q1.norm_sum_leftRegular_eq_card_of_finiteFoelner
#print axioms Q1.indicatorCoefficient_apply
#print axioms Q1.support_indicatorCoefficient
#print axioms Q1.coefficientL2Norm_indicator_sq
#print axioms Q1.coefficientL2Norm_indicator
#print axioms Q1.regularConvolution_indicator
#print axioms Q1.norm_regularConvolution_indicator_of_hasInvariantMean
#print axioms Q1.amenable_subset_card_le_reducedBallRho_sq
#print axioms Q1.amenable_subgroupBall_card_le_reducedRho_sq
#print axioms Q1.no_amenable_confined_subgroup_of_reducedSRD
#print axioms Q1.no_amenable_confined_subgroup_of_reducedRD
#print axioms Q1.no_amenable_confined_subgroup_word_srd
#print axioms Q1.no_amenable_confined_subgroup_word_rd
#print axioms Q1.ballCoefficient_support
#print axioms Q1.ballCoefficient_apply
#print axioms Q1.ballCoefficient_restrict
#print axioms Q1.ballCoefficient_add
#print axioms Q1.ballCoefficient_smul
#print axioms Q1.continuous_ballCoefficientNorm
#print axioms Q1.norm_coordinate_le_coefficientL2Norm
#print axioms Q1.isCompact_ballCoefficient_unitSphere
#print axioms Q1.continuous_ballRegularConvolution_norm
#print axioms Q1.unitCoefficient_support
#print axioms Q1.norm_inverse_coefficientL2Norm
#print axioms Q1.coefficientL2Norm_unitCoefficient
#print axioms Q1.norm_regularConvolution_unitCoefficient
#print axioms Q1.ballCoefficient_unitSphere_nonempty
#print axioms Q1.reducedBallRho_attained
#print axioms Q1.reducedBallRho_attained_ratio
#print axioms Q1.reducedBallRho_isGreatest
#print axioms Q1.reducedRho_attained
#print axioms Q1.reducedRho_wordLength_attained
#print axioms Q1.GroupL2
#print axioms Q1.leftRegularIsometry
#print axioms Q1.leftRegular
#print axioms Q1.regularConvolution
#print axioms Q1.coefficientVector
#print axioms Q1.coefficientL2Norm
#print axioms Q1.reducedRatio
#print axioms Q1.reducedRatios
#print axioms Q1.reducedBallRho
#print axioms Q1.reducedRho
#print axioms Q1.ReducedRD
#print axioms Q1.ReducedSRD
#print axioms Q1.nonzeroReducedRatios
#print axioms Q1.indicatorVector
#print axioms Q1.indicatorCoefficient
#print axioms Q1.ballCoefficient
#print axioms Q1.ballCoefficientVector
#print axioms Q1.ballRegularConvolution
#print axioms Q1.unitCoefficient
#print axioms Q1.leftRegular_one_eq_one
#print axioms Q1.leftRegular_mul_eq_mul
#print axioms Q1.star_leftRegular
#print axioms Q1.leftRegular_mem_finiteRegularSpan
#print axioms Q1.regularConvolution_mem_finiteRegularSpan
#print axioms Q1.mem_finiteRegularSpan_iff
#print axioms Q1.mul_mem_finiteRegularSpan
#print axioms Q1.star_mem_finiteRegularSpan
#print axioms Q1.mem_reducedGroupAlgebra_iff
#print axioms Q1.regularConvolution_mem_reducedGroupAlgebra
#print axioms Q1.reducedPolynomial_coe
#print axioms Q1.norm_reducedPolynomial
#print axioms Q1.exists_reducedPolynomial_near
#print axioms Q1.regularRepresentation_apply
#print axioms Q1.reducedLeftRegular_coe
#print axioms Q1.norm_reducedLeftRegular
#print axioms Q1.rightRegular_apply
#print axioms Q1.rightRegular_single
#print axioms Q1.leftRegular_commute_rightRegular
#print axioms Q1.regularConvolution_commute_rightRegular
#print axioms Q1.reducedGroupAlgebra_commute_rightRegular
#print axioms Q1.norm_groupIdentityVector
#print axioms Q1.reducedGroupAlgebra_eq_zero_of_delta
#print axioms Q1.regularVectorState_apply
#print axioms Q1.norm_regularVectorState_apply_le
#print axioms Q1.regularVectorState_one
#print axioms Q1.regularVectorState_regularConvolution
#print axioms Q1.regularVectorState_star_mul_self
#print axioms Q1.reducedVectorState_apply
#print axioms Q1.reducedVectorState_reducedPolynomial
#print axioms Q1.reducedVectorState_faithful
#print axioms Q1.conjugationAverage_zero
#print axioms Q1.conjugationAverage_one
#print axioms Q1.conjugationAverage_add
#print axioms Q1.conjugationAverage_sub
#print axioms Q1.conjugationAverage_smul
#print axioms Q1.conjugationAverage_sum
#print axioms Q1.norm_innerConjugation_le
#print axioms Q1.norm_conjugationAverage_le
#print axioms Q1.hasConjugationAveraging_of_dense
#print axioms Q1.twoSidedIdeal_complex_smul_mem
#print axioms Q1.conjugationAverage_mem
#print axioms Q1.twoSidedIdeal_eq_top_of_isUnit_mem
#print axioms Q1.twoSidedIdeal_eq_bot_or_top_of_conjugationAveraging
#print axioms Q1.cStarSimple_of_conjugationAveraging
#print axioms Q1.packedConjugates_injective
#print axioms Q1.card_packedConjugateSet
#print axioms Q1.packedConjugateSet_subset_ball
#print axioms Q1.conjugationAverage_leftRegular_eq
#print axioms Q1.norm_conjugationAverage_leftRegular_le
#print axioms Q1.norm_conjugationAverage_regularConvolution_le
#print axioms Q1.logarithmic_conjugate_packing_of_trivial_radical
#print axioms Q1.finite_zero_identity_averaging
#print axioms Q1.finite_coefficient_averaging
#print axioms Q1.reduced_conjugationAverage_coe
#print axioms Q1.dense_reducedPolynomial
#print axioms Q1.reducedGroup_hasConjugationAveraging
#print axioms Q1.cStarSimple_of_reducedSRD
#print axioms Q1.cStarSimple_of_reducedRD
#print axioms Q1.q1_srd
#print axioms Q1.q1_rd
#print axioms Q1.RegularOperator
#print axioms Q1.finiteRegularSpan
#print axioms Q1.finiteRegularAlgebra
#print axioms Q1.reducedGroupAlgebra
#print axioms Q1.ReducedGroupCStarAlgebra
#print axioms Q1.reducedPolynomial
#print axioms Q1.regularRepresentation
#print axioms Q1.reducedLeftRegular
#print axioms Q1.rightRegularIsometry
#print axioms Q1.rightRegular
#print axioms Q1.groupIdentityVector
#print axioms Q1.regularVectorState
#print axioms Q1.reducedVectorState
#print axioms Q1.CStarSimple
#print axioms Q1.conjugationAverage
#print axioms Q1.HasConjugationAveraging
#print axioms Q1.packedConjugateSet

#print axioms Q1.instCStarAlgebraSubtypeRegularOperatorMemStarSubalgebraComplexReducedGroupCStarAlgebra

#print axioms Q1.instCompleteSpaceSubtypeRegularOperatorMemStarSubalgebraComplexReducedGroupCStarAlgebra

#print axioms Q1.instNontrivialSubtypeRegularOperatorMemStarSubalgebraComplexReducedGroupCStarAlgebra

#print axioms Q1.reducedGroupAlgebra_isClosed
